classdef DefaultParameters
    %DefaultParameters is a class containing static constant variables used
    %throughout the preprocessing. Note that not every field is a parameter 
    %to preprocessing, some are simply constant values that are kept here
    %for better maintenance.
    %
    % Copyright (C) 2017  Amirreza Bahreini, amirreza.bahreini@uzh.ch
    % 
    % This program is free software: you can redistribute it and/or modify
    % it under the terms of the GNU General Public License as published by
    % the Free Software Foundation, either version 3 of the License, or
    % (at your option) any later version.
    % 
    % This program is distributed in the hope that it will be useful,
    % but WITHOUT ANY WARRANTY; without even the implied warranty of
    % MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    % GNU General Public License for more details.
    % 
    % You should have received a copy of the GNU General Public License
    % along with this program.  If not, see <http://www.gnu.org/licenses/>.
    properties(Constant)        
        filter_params = struct('notch_freq', 50, ...
                                'notch_eu', 50, ...
                                'notch_us', 60, ...
                                'notch_other', [], ...
                                'high_freq', 0.5, ...
                                'high_order', [], ... % Will use default
                                'low_freq', -1, ... % Will desactivate the operation
                                'low_order', [], ... % Will use default
                                'run_message', 'Perform Filtering...');

        channel_rejection_params = struct('kurt_thresh', 3,...
                                'prob_thresh', 4,...
                                'spec_thresh', 4,...
                                'exclude_chans', [], ...
                                'rar', 0, ...
                                'rar_url', 'https://github.com/VisLab/EEG-Clean-Tools/archive/master.zip', ...
                                'run_message', 'Finding bad channels...');
        
        interpolation_params = struct('method', 'spherical');
        
        pca_params = struct('lambda', [], ...  % Will use default
                            'tol', 1e-7, ...
                            'maxIter', 1000, ...
                            'pca_url', 'http://perception.csl.illinois.edu/matrix-rank/Files/inexact_alm_rpca.zip', ...
                            'run_message', 'Performing PCA  (this may take a while...)');
                        
        ica_params = struct('chanloc_map', containers.Map, ...
                            'bool', 0, ...
                            'req_chan_labels', ['Cz'; 'Fz'; 'Pz'], ...
                            'run_message', 'Performing ICA  (this may take a while...)')
                    
        eog_regression_params = struct('perform_eog_regression', 1, ...
                            'eog_chans', '', ...
                            'run_message', 'Perform EOG Regression...');
                        
        channel_reduction_params = struct('perform_reduce_channels', 1, ...
                            'tobe_excluded_chans', '');
                        
        eeg_system = struct('name', 'EGI',...
                            'sys10_20', 0, ...
                            'sys10_20_file', 'standard-10-5-cap385.elp',...
                            'EGI_name', 'EGI',...
                            'Others_name', 'Others', ...
                            'loc_file', '', ...
                            'ref_chan', [], ...
                            'file_loc_type', '');
                        
        general_params = struct('original_file', '', ...
                            'reduced_name', 'reduced');                
                    
    end
end